apiVersion: v1
kind: Service
metadata:
  name: k8sreq-duplicator-controller
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9556
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    control-plane: controller-manager
  type: ClusterIP
