apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: requestclones-viewer-role
rules:
- apiGroups:
  - proxy.infra.doodle.com
  resources:
  - requestclones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.infra.doodle.com
  resources:
  - requestclones/status
  verbs:
  - get
